### ISSUE TITLE
Error on :GitLog

### ISSUE THREAD

**Issue by askedrelic** [kablamo/vim-git-log#1]
Hey, cool plugin! I have never found Fugitive's log functionality to be optimal, this looks like a good improvement

I get the following error when running :GitLog, on a new vim session, with a regular git repo. The buffer opens and GitLog works from here, but remains in a modified state
http://asktherelic.com/priv/4z1Dw.png

System:
OSX, homebrew
Latest vim 7.3, http://asktherelic.com/priv/pWREO.png
Latest fugitive
vimrc here: https://github.com/askedrelic/homedir/blob/master/.vimrc

**Comment by kablamo** [comment]
Thanks!  I suspect tpope uses the browser to browse his history and repo and thats why Fugitive works the way it does.  I wanted a way to browse using vim.

Hmmm... I'm not getting that error.  Can you do a pull and try again?  I seem to remember this error from an older version.

**Comment by askedrelic** [comment]
Yup, that fixed it. I found this through the vim-scripts clone repo (https://github.com/vim-scripts), it was probably out of date. Thanks!
